In [1]:
import numpy as np

In [3]:
np.arange(0, 101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
from numpy import random

In [7]:
np.random.randn(2, 3)

array([[-0.61955271,  1.34027169,  0.01203639],
       [ 1.46863467,  2.78357673,  0.75162849]])

In [8]:
arr = np.arange(10)

In [9]:
arr.shape

(10,)

In [10]:
arr.dtype

dtype('int64')

In [11]:
np.array([1, 2, 3])

array([1, 2, 3])

In [14]:
np.array([[1, 2, 3], [ 4, 5, 6], [7, 8, 9]]).ndim

2

In [16]:
np.zeros((1, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [17]:
np.zeros((4, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
np.empty((1, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [19]:
np.empty((3, 10))

array([[ -1.72723371e-077,  -1.49457971e-154,   7.90505033e-323,
          0.00000000e+000,   0.00000000e+000,   5.02034658e+175,
          1.75981060e+030,   5.48654702e-057,   1.65398344e+011,
          7.40675370e-038],
       [  1.47763641e+248,   1.16096346e-028,   7.69165785e+218,
          1.35617292e+248,   5.03514176e-038,   1.63330667e-042,
          9.72237326e+015,   5.49892962e-057,   4.25765026e-096,
          6.32299154e+233],
       [  6.48224638e+170,   5.22411352e+257,   5.74020278e+180,
          8.37174974e-144,   1.41529402e+161,   9.16651763e-072,
          5.38016465e+097,   7.13184651e-067,   7.43423022e-144,
          2.19524848e-314]])

In [20]:
np.arange(0, 16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
data = np.zeros((3, 6))

In [23]:
np.ones_like(data)

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [24]:
np.zeros_like(data)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [25]:
np.ones_like(data)

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [26]:
np.empty_like(data)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [29]:
np.array([1, 2, 3], dtype=np.float64)

array([ 1.,  2.,  3.])

In [30]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [31]:
np.random.randn(2, 3)

array([[-0.75360713,  0.50331369, -0.37209468],
       [ 0.91439723,  0.23053612, -1.14338254]])

In [33]:
np.array([1, 2, 3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [34]:
data.shape

(3, 6)

In [35]:
np.array([1, 2, 3])

array([1, 2, 3])

In [36]:
np.array([True, False], dtype=np.bool)

array([ True, False], dtype=bool)

In [37]:
data.dtype

dtype('float64')

In [38]:
np.zeros((4, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [39]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [40]:
arr2.ndim

2

In [41]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.array(["a", "b"], dtype=np.string_)

array([b'a', b'b'], 
      dtype='|S1')

In [44]:
np.zeros((1, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [46]:
np.empty((3, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [47]:
arr = np.array([1, 2, 3, 4, 5])

In [49]:
arr.astype(np.float)

array([ 1.,  2.,  3.,  4.,  5.])

In [50]:
np.empty((1, 10))

array([[  0.00000000e+000,   4.94065646e-324,   9.88131292e-324,
          1.48219694e-323,   1.97626258e-323,   2.47032823e-323,
          2.96439388e-323,   3.45845952e-323,   3.95252517e-323,
          4.44659081e-323]])

In [52]:
np.array(["a", "b"], dtype=np.string_)

array([b'a', b'b'], 
      dtype='|S1')

In [53]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [54]:
np.arange(0, 16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
arr

array([1, 2, 3, 4, 5])

In [56]:
arr.astype(np.float)

array([ 1.,  2.,  3.,  4.,  5.])

In [61]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [62]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [63]:
np.array([1, 2, 3], dtype=arr.dtype)

array([1, 2, 3])

In [64]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [66]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [67]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [69]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [70]:
np.ones_like(arr)

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
np.empty_like(arr)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [72]:
np.zeros_like(arr)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [73]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])


In [74]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [75]:
arr + arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [76]:
np.array([1, 2], dtype=np.int32)

array([1, 2], dtype=int32)

In [77]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [78]:
arr / 3

array([[ 0.33333333,  0.66666667,  1.        ],
       [ 1.33333333,  1.66666667,  2.        ]])

In [79]:
arr ** 3

array([[   1.,    8.,   27.],
       [  64.,  125.,  216.]])

In [81]:
arr > arr

array([[False, False, False],
       [False, False, False]], dtype=bool)

In [83]:
np.array([1, 2, 3], dtype=np.float64)

array([ 1.,  2.,  3.])

In [84]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [85]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr[1]

1

In [87]:
np.array([True, False], dtype=np.bool)

array([ True, False], dtype=bool)

In [88]:
np.array(["s", "v"], dtype=np.string_)

array([b's', b'v'], 
      dtype='|S1')

In [89]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr[2:3]

array([2])

In [92]:
arr[2:5] = 100

In [93]:
arr[2:5]

array([100, 100, 100])

In [94]:
arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9])

In [95]:
arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9])

In [96]:
arr.astype(np.float64)

array([   0.,    1.,  100.,  100.,  100.,    5.,    6.,    7.,    8.,    9.])

In [97]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [99]:
numeric_strings.astype(np.string_)

array([b'1.25', b'-9.6', b'42'], 
      dtype='|S4')

In [100]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [101]:
arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9])

In [102]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])


In [103]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [106]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [107]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [108]:
arr / arr

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [109]:
arr == arr

array([[ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [110]:
arr = np.arange(10)

In [111]:
arr[:] = 100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [113]:
arr[2:8].copy()

array([100, 100, 100, 100, 100, 100])

In [114]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [117]:
arr2d[0, 2] = 111
arr2d

array([[  1,   2, 111],
       [  4,   5,   6],
       [  7,   8,   9]])

In [118]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [119]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
arr3d[0:3] = 100
arr3d

array([[[100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100]]])

In [123]:
arr = np.arange(10)

In [124]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [125]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [127]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [132]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [133]:
arr2d[1, :2]

array([4, 5])

In [134]:
arr = np.arange(10)

In [135]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
arr[2:3] = 10

In [137]:
arr

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [138]:
arr[:] = 100

In [139]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [140]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [142]:
arr2d[0, 2]

3

In [145]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
arr2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [146]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
arr2d[:2, 2]

array([3, 6])

In [150]:
arr2d[1, :2]

array([4, 5])

In [152]:
arr2d[:2, 2]

array([3, 6])

In [153]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [156]:
arr2d[2]

array([7, 8, 9])

In [157]:
arr2d[1, :2]

array([4, 5])

In [158]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [161]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [162]:
arr2d[1, :2]

array([4, 5])

In [166]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [167]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [168]:
arr2d[:, 0:1]

array([[1],
       [4],
       [7]])

In [169]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [173]:
data = np.random.randn(7, 4)

In [174]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [175]:
data[names == "Bob"]

array([[ 0.12930453,  0.80018385,  1.1636799 , -1.5788841 ],
       [-0.0233313 ,  1.25944308, -0.12041733, -0.90320046]])

In [177]:
arr2d[1, :2]

array([4, 5])

In [178]:
arr2d[:2,2]

array([3, 6])

In [179]:
arr2d[2]

array([7, 8, 9])

In [181]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [182]:
data[names == "Bob"]

array([[ 0.12930453,  0.80018385,  1.1636799 , -1.5788841 ],
       [-0.0233313 ,  1.25944308, -0.12041733, -0.90320046]])

In [183]:
data[names != "Bob"]

array([[-1.53325316, -0.17750325,  1.36160006, -1.59754234],
       [-0.02488857, -0.90508021, -0.02437011, -1.25432987],
       [-0.76363498,  0.26461081,  0.27375866, -0.87669985],
       [-0.77686509, -1.20397952,  0.66580793, -0.77895477],
       [-0.18854123, -0.876035  , -0.30359317,  0.58363729]])

In [184]:
data[~(names == "Bob")]

array([[-1.53325316, -0.17750325,  1.36160006, -1.59754234],
       [-0.02488857, -0.90508021, -0.02437011, -1.25432987],
       [-0.76363498,  0.26461081,  0.27375866, -0.87669985],
       [-0.77686509, -1.20397952,  0.66580793, -0.77895477],
       [-0.18854123, -0.876035  , -0.30359317,  0.58363729]])

In [185]:
arr2d[1, :2]

array([4, 5])

In [186]:
data = np.random.randn(7, 4)

In [188]:
data[data < 0] = 0

In [189]:
data

array([[ 0.        ,  0.        ,  1.05193929,  0.        ],
       [ 0.        ,  0.        ,  0.77198196,  0.28138656],
       [ 0.        ,  0.        ,  0.45683317,  0.        ],
       [ 0.        ,  2.75366959,  0.        ,  0.60021631],
       [ 1.13566673,  0.        ,  1.1228914 ,  0.06937685],
       [ 0.        ,  0.        ,  0.93424804,  0.        ],
       [ 0.52210845,  1.67289764,  0.96837474,  1.46354113]])

In [191]:
arr2d[:, 0:1]

array([[1],
       [4],
       [7]])

In [192]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [193]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [195]:
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [196]:
data

array([[ 0.25283611,  1.10183399,  1.74762675,  0.89392426],
       [ 0.27545856,  1.25982158, -0.73862768, -0.07018407],
       [ 0.13811548,  1.671604  ,  1.2411366 , -0.3542004 ],
       [-1.56203359, -0.88982688, -0.13980278, -1.28302719],
       [ 0.90889967, -0.32263479,  0.34528679, -0.34851854],
       [ 0.73389611,  1.38547778,  1.53974596,  1.39511125],
       [-0.7468751 , -1.47120524, -0.03849186, -1.40121761]])

In [197]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [202]:
data[names == "Joe"]

array([[ 0.27545856,  1.25982158, -0.73862768, -0.07018407],
       [ 0.73389611,  1.38547778,  1.53974596,  1.39511125],
       [-0.7468751 , -1.47120524, -0.03849186, -1.40121761]])

In [204]:
data[names == "Bob"]

array([[ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.]])

In [205]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

In [206]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [209]:
arr[[4, 3, 0, 6], [1, 2, 3, 3]]

array([ 4.,  3.,  0.,  6.])

In [210]:
data[(names == "Bob") | (names == "Will") ]

array([[ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.]])

In [3]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [2]:
import numpy as np

In [4]:
arr1 > arr2

array([[ True, False,  True],
       [False,  True, False]], dtype=bool)

In [5]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [6]:
arr2d[:2, 2]

array([3, 6])

In [7]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

In [8]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [9]:
arr[[-1, -2]]

array([[ 7.,  7.,  7.,  7.],
       [ 6.,  6.,  6.,  6.]])

In [10]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
arr2 = np.arange(32).reshape((8, 4))

In [12]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
arr2[[0, 1, 2]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [17]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [18]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [19]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [20]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [21]:
numeric_strings.astype(np.float64)

array([  1.25,  -9.6 ,  42.  ])

In [22]:
np.arange(0, 32).reshape((8, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [23]:
np.array([1, 2, 3])

array([1, 2, 3])

In [24]:

arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [27]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [28]:
arr2d[2]

array([7, 8, 9])

In [29]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [30]:
arr = np.arange(32).reshape((8, 4))

In [32]:
arr[[1, 2, 3], [1, 2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [33]:
np.empty((3, 10))

array([[ -3.10503618e+231,  -3.10503618e+231,   7.41098469e-323,
          0.00000000e+000,   2.12199579e-314,   5.02034658e+175,
          3.51838811e+030,   6.13987097e-057,   2.51961119e-071,
          2.10897532e-052],
       [  1.47763641e+248,   1.16096346e-028,   7.69165785e+218,
          1.35617292e+248,   6.10966392e-062,   5.64235968e-038,
          8.97631298e-067,   4.66535516e-062,   4.26490836e-096,
          6.32299154e+233],
       [  6.48224638e+170,   5.22411352e+257,   5.74020278e+180,
          8.37174974e-144,   1.41529402e+161,   9.16651763e-072,
          3.45861069e+097,   5.16008880e-062,   8.06864023e-144,
          2.15398360e-308]])

In [34]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

In [35]:
arr[-1]

array([ 7.,  7.,  7.,  7.])

In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)


In [39]:
data[names == "Joe"]

array([[ 1.69740816, -0.57640403,  0.13679004,  1.1516187 ],
       [-0.26044901,  0.32127298, -0.28913047,  0.24471182],
       [-0.90494793, -0.53265158,  1.13072602, -0.13095133]])

In [41]:
arr[2:4]

array([[ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.]])

In [42]:
np.sqrt(arr)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356],
       [ 1.73205081,  1.73205081,  1.73205081,  1.73205081],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.23606798,  2.23606798,  2.23606798,  2.23606798],
       [ 2.44948974,  2.44948974,  2.44948974,  2.44948974],
       [ 2.64575131,  2.64575131,  2.64575131,  2.64575131]])

In [43]:
arr.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [44]:
data[~(names == "Bob")]

array([[ 1.69740816, -0.57640403,  0.13679004,  1.1516187 ],
       [ 1.10883112, -1.09665111,  0.13603796,  1.34745424],
       [ 2.56185064,  2.11750777, -0.88933918,  1.22921066],
       [-0.26044901,  0.32127298, -0.28913047,  0.24471182],
       [-0.90494793, -0.53265158,  1.13072602, -0.13095133]])

In [46]:
np.exp(arr)

array([[  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00],
       [  2.71828183e+00,   2.71828183e+00,   2.71828183e+00,
          2.71828183e+00],
       [  7.38905610e+00,   7.38905610e+00,   7.38905610e+00,
          7.38905610e+00],
       [  2.00855369e+01,   2.00855369e+01,   2.00855369e+01,
          2.00855369e+01],
       [  5.45981500e+01,   5.45981500e+01,   5.45981500e+01,
          5.45981500e+01],
       [  1.48413159e+02,   1.48413159e+02,   1.48413159e+02,
          1.48413159e+02],
       [  4.03428793e+02,   4.03428793e+02,   4.03428793e+02,
          4.03428793e+02],
       [  1.09663316e+03,   1.09663316e+03,   1.09663316e+03,
          1.09663316e+03]])

In [47]:
np.zeros_like(data)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [49]:
arr2d[0, 2]

3

In [51]:
np.maximum(x, y)

array([-0.57439669,  1.53343115,  3.07153608, -0.5832954 ,  1.23955492,
        0.21332307,  1.04075229,  0.02928185])

In [50]:
x = np.random.randn(8)
y = np.random.randn(8)

In [52]:
np.sqrt(arr)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356],
       [ 1.73205081,  1.73205081,  1.73205081,  1.73205081],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.23606798,  2.23606798,  2.23606798,  2.23606798],
       [ 2.44948974,  2.44948974,  2.44948974,  2.44948974],
       [ 2.64575131,  2.64575131,  2.64575131,  2.64575131]])

In [53]:
np.ones_like(arr)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [54]:
np.abs(arr)

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [55]:
np.arange(0, 32).reshape(8, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [56]:
arr.T

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.]])

In [57]:
np.sqrt(arr)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356],
       [ 1.73205081,  1.73205081,  1.73205081,  1.73205081],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.23606798,  2.23606798,  2.23606798,  2.23606798],
       [ 2.44948974,  2.44948974,  2.44948974,  2.44948974],
       [ 2.64575131,  2.64575131,  2.64575131,  2.64575131]])

In [59]:
arr[:] = 100
arr

array([[ 100.,  100.,  100.,  100.],
       [ 100.,  100.,  100.,  100.],
       [ 100.,  100.,  100.,  100.],
       [ 100.,  100.,  100.,  100.],
       [ 100.,  100.,  100.,  100.],
       [ 100.,  100.,  100.,  100.],
       [ 100.,  100.,  100.,  100.],
       [ 100.,  100.,  100.,  100.]])

In [60]:
np.square(arr)

array([[ 10000.,  10000.,  10000.,  10000.],
       [ 10000.,  10000.,  10000.,  10000.],
       [ 10000.,  10000.,  10000.,  10000.],
       [ 10000.,  10000.,  10000.,  10000.],
       [ 10000.,  10000.,  10000.,  10000.],
       [ 10000.,  10000.,  10000.,  10000.],
       [ 10000.,  10000.,  10000.,  10000.],
       [ 10000.,  10000.,  10000.,  10000.]])

In [61]:
data[names == "Bob"]

array([[-0.33604898,  0.61376355,  0.29762159,  0.89116697],
       [-0.70904245, -0.01034172,  0.40812927,  0.2878617 ]])

In [62]:
np.exp(arr)

array([[  2.68811714e+43,   2.68811714e+43,   2.68811714e+43,
          2.68811714e+43],
       [  2.68811714e+43,   2.68811714e+43,   2.68811714e+43,
          2.68811714e+43],
       [  2.68811714e+43,   2.68811714e+43,   2.68811714e+43,
          2.68811714e+43],
       [  2.68811714e+43,   2.68811714e+43,   2.68811714e+43,
          2.68811714e+43],
       [  2.68811714e+43,   2.68811714e+43,   2.68811714e+43,
          2.68811714e+43],
       [  2.68811714e+43,   2.68811714e+43,   2.68811714e+43,
          2.68811714e+43],
       [  2.68811714e+43,   2.68811714e+43,   2.68811714e+43,
          2.68811714e+43],
       [  2.68811714e+43,   2.68811714e+43,   2.68811714e+43,
          2.68811714e+43]])

In [63]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [64]:
np.log(arr)

array([[ 4.60517019,  4.60517019,  4.60517019,  4.60517019],
       [ 4.60517019,  4.60517019,  4.60517019,  4.60517019],
       [ 4.60517019,  4.60517019,  4.60517019,  4.60517019],
       [ 4.60517019,  4.60517019,  4.60517019,  4.60517019],
       [ 4.60517019,  4.60517019,  4.60517019,  4.60517019],
       [ 4.60517019,  4.60517019,  4.60517019,  4.60517019],
       [ 4.60517019,  4.60517019,  4.60517019,  4.60517019],
       [ 4.60517019,  4.60517019,  4.60517019,  4.60517019]])

In [65]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i


In [66]:
arr[[1, 3, 2]]

array([[ 1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.],
       [ 2.,  2.,  2.,  2.]])

In [67]:
np.log(arr)

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([[       -inf,        -inf,        -inf,        -inf],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.69314718,  0.69314718,  0.69314718,  0.69314718],
       [ 1.09861229,  1.09861229,  1.09861229,  1.09861229],
       [ 1.38629436,  1.38629436,  1.38629436,  1.38629436],
       [ 1.60943791,  1.60943791,  1.60943791,  1.60943791],
       [ 1.79175947,  1.79175947,  1.79175947,  1.79175947],
       [ 1.94591015,  1.94591015,  1.94591015,  1.94591015]])

In [68]:
np.sqrt(arr)

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.41421356,  1.41421356,  1.41421356,  1.41421356],
       [ 1.73205081,  1.73205081,  1.73205081,  1.73205081],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.23606798,  2.23606798,  2.23606798,  2.23606798],
       [ 2.44948974,  2.44948974,  2.44948974,  2.44948974],
       [ 2.64575131,  2.64575131,  2.64575131,  2.64575131]])

In [69]:
arr = np.random.randn(7) * 5

In [70]:
arr

array([-10.3681489 ,   1.49198875,  -0.88793283,  -6.64507999,
         5.63014202,  -4.31982274,  -7.44901902])

In [71]:
np.where(arr > 0, 1, -1)

array([-1,  1, -1, -1,  1, -1, -1])

In [72]:
np.sign(arr)

array([-1.,  1., -1., -1.,  1., -1., -1.])

In [73]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [74]:
arr * 3

array([[  3.,   6.,   9.],
       [ 12.,  15.,  18.]])

In [75]:
np.ceil(arr)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [76]:
np.maximum(x, y)

array([-0.57439669,  1.53343115,  3.07153608, -0.5832954 ,  1.23955492,
        0.21332307,  1.04075229,  0.02928185])

In [77]:
arr = np.random.randn(7) * 5

In [78]:
arr = np.arange(10)

In [80]:
arr[:] = 100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [81]:
np.abs(arr)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [82]:
np.floor(arr)

array([ 100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.])

In [83]:
arr.dtype

dtype('int64')

In [87]:
np.rint(arr)

array([ 100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.])

In [88]:
np.isnan(arr)

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [89]:
np.log(arr)

array([ 4.60517019,  4.60517019,  4.60517019,  4.60517019,  4.60517019,
        4.60517019,  4.60517019,  4.60517019,  4.60517019,  4.60517019])

In [90]:
arr + arr 

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [91]:
np.add(arr, arr)

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [92]:
np.rint(arr)

array([ 100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.,  100.])

In [93]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.subtract(arr, arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [95]:
data[names == "Bob"]

array([[-0.33604898,  0.61376355,  0.29762159,  0.89116697],
       [-0.70904245, -0.01034172,  0.40812927,  0.2878617 ]])

In [96]:
np.multiply(arr, arr)

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000])

In [97]:
np.zeros((4, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [98]:
np.divide(arr, arr)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
np.power(arr, arr)

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in power
  if __name__ == '__main__':


array([-9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808])

In [101]:
arr = np.array([1, 2, 3, 4, 5])

In [103]:
arr.astype(np.float64)

array([ 1.,  2.,  3.,  4.,  5.])

In [104]:
np.sign(arr)

array([1, 1, 1, 1, 1])

In [106]:
np.power(arr , 2)

array([ 1,  4,  9, 16, 25])

In [107]:
arr ** 2

array([ 1,  4,  9, 16, 25])

In [108]:
np.maximum(arr1, arr2)

ValueError: operands could not be broadcast together with shapes (2,3) (8,4) 

In [109]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [110]:
arr2d[1, :2]

array([4, 5])

In [111]:
np.sign(arr)

array([1, 1, 1, 1, 1])

In [112]:
np.ceil(arr)

array([ 1.,  2.,  3.,  4.,  5.])

In [113]:
arr.dtype

dtype('int64')

In [114]:
np.floor(arr)

array([ 1.,  2.,  3.,  4.,  5.])

In [115]:
np.isnan(arr)

array([False, False, False, False, False], dtype=bool)

In [117]:
np.multiply(arr, arr)

array([ 1,  4,  9, 16, 25])

In [118]:
np.add(arr, arr)

array([ 2,  4,  6,  8, 10])

In [119]:
np.subtract(arr, arr)

array([0, 0, 0, 0, 0])

In [120]:
np.rint(arr)

array([ 1.,  2.,  3.,  4.,  5.])

In [121]:
np.round(arr)

array([1, 2, 3, 4, 5])

In [122]:
np.zeros((1, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [123]:
np.minimum(arr, arr)

array([1, 2, 3, 4, 5])

In [125]:
data[names == "Bob"]

array([[-0.33604898,  0.61376355,  0.29762159,  0.89116697],
       [-0.70904245, -0.01034172,  0.40812927,  0.2878617 ]])

In [128]:
np.mod(arr, arr)

array([0, 0, 0, 0, 0])

In [129]:
np.array([True, False], dtype=np.bool)

array([ True, False], dtype=bool)

In [130]:
np.rint(arr)

array([ 1.,  2.,  3.,  4.,  5.])

In [131]:
np.greater(arr, arr)

array([False, False, False, False, False], dtype=bool)

In [ ]:
np.greater_equal

In [ ]:
np.less

In [ ]:
np.less_equal

In [132]:
np.array([1, 2, 3], dtype=np.str_)

array(['1', '2', '3'], 
      dtype='<U1')

In [134]:
np.logical_and([True, False], [True, False])

array([ True, False], dtype=bool)

In [135]:
arr1 = np.array([True, False, True])
arr2 = np.array([False, False, True])


In [137]:
np.logical_and(arr1, arr2)

array([False, False,  True], dtype=bool)

In [138]:
arr1 & arr2

array([False, False,  True], dtype=bool)

In [139]:
np.sign(arr)

array([1, 1, 1, 1, 1])

In [141]:
np.logical_or(arr1, arr2)

array([ True, False,  True], dtype=bool)

In [142]:
arr1 | arr2

array([ True, False,  True], dtype=bool)

In [143]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
np.logical_and(arr1, arr2)

array([False, False,  True], dtype=bool)

In [145]:
arr1 & arr2

array([False, False,  True], dtype=bool)

In [146]:
arr / 2

array([ 0.5,  1. ,  1.5,  2. ,  2.5])

In [147]:
np.logical_not(arr1)

array([False,  True, False], dtype=bool)

In [149]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [150]:
np.sqrt(xs ** 2 + ys ** 2)

NameError: name 'xs' is not defined

In [151]:
arr2d[:, 1:2]

array([[2],
       [5],
       [8]])

In [153]:
arr2d[1, :2]

array([4, 5])

In [154]:
np.empty((1, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [155]:
np.array([1, 2, 3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [157]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [158]:
np.rint(arr)

array([ 1.,  2.,  3.,  4.,  5.])

In [159]:
np.random.randn(2, 3)

array([[ 0.54493063, -0.7078802 ,  0.3356182 ],
       [ 0.56320829,  1.37535093,  0.73577443]])

In [161]:
np.array([1, 2, 3], dtype=np.float)

array([ 1.,  2.,  3.])

In [162]:
data = np.random.randn(2, 3)

In [163]:
data.shape

(2, 3)

In [164]:
np.array([1, 2, 3], dtype=np.string_)

array([b'1', b'2', b'3'], 
      dtype='|S1')

In [ ]:
np.greater
np.greater_equal
np.less
np.less_equal
np.equal

In [165]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [166]:
arr2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [167]:
arr2d.ndim

2

In [168]:
np.logical_or(arr1, arr2)

array([ True, False,  True], dtype=bool)

In [169]:
arr1 | arr2

array([ True, False,  True], dtype=bool)

In [170]:
np.logical_and(arr1, arr2)

array([False, False,  True], dtype=bool)

In [171]:
arr1 & arr2

array([False, False,  True], dtype=bool)

In [173]:
np.logical_not(arr2)

array([ True, False,  True], dtype=bool)

In [174]:
~ arr1

array([False,  True, False], dtype=bool)

In [175]:
arr2d[1, :2]

array([4, 5])

In [176]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [177]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [178]:
xarr[cond]

array([ 1.1,  1.3,  1.4])

In [180]:
np.where(cond, xarr, yarr)

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [182]:
arr = np.random.randn(4, 4)
arr

array([[ 0.37908538,  0.58048333, -0.28195302,  0.3078368 ],
       [-0.6438837 ,  1.20338044,  0.40949511,  1.85460345],
       [ 0.9598047 ,  1.57363398, -0.34611837,  1.00099855],
       [ 0.73437274, -0.78052092,  1.11916863, -1.92297913]])