In [3]:
np.rint(arr)

NameError: name 'arr' is not defined

In [2]:
import numpy as np

In [4]:
np.rint(arr)

NameError: name 'arr' is not defined

In [5]:
data = np.zeros((3, 6))

In [6]:
np.zeros_like(data)

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [8]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
arr2d[2]

array([7, 8, 9])

In [11]:
arr = np.random.randn(4, 4)
arr

array([[ 0.26780474, -1.5142533 ,  0.50136675, -2.29809915],
       [ 1.5927355 , -1.79632221,  0.99310544, -0.27656541],
       [ 0.56811174,  1.12039962, -0.29175383,  0.87286379],
       [ 1.04910264,  0.68717333,  1.42044881, -0.14427159]])

In [13]:
np.where(arr > 0, 2, arr)

array([[ 2.        , -1.5142533 ,  2.        , -2.29809915],
       [ 2.        , -1.79632221,  2.        , -0.27656541],
       [ 2.        ,  2.        , -0.29175383,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.14427159]])

In [14]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [15]:
np.array([1, 2, 3], dtype=calibers.dtype)

array([ 1.,  2.,  3.])

In [16]:
np.floor(arr)

array([[ 0., -2.,  0., -3.],
       [ 1., -2.,  0., -1.],
       [ 0.,  1., -1.,  0.],
       [ 1.,  0.,  1., -1.]])

In [17]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
arr.sort(axis=0)

In [19]:
arr.std(axis=0)

array([ 0.5020455 ,  1.29252513,  0.63642962,  1.14983236])

In [21]:
np.random.randn(2, 2)

array([[ 0.82516933, -1.51467936],
       [ 0.8642516 ,  1.23173432]])

In [22]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))

arr2 = np.random.randn(3, 2)


In [24]:
np.hstack([arr1, arr2])

array([[ 0.        ,  1.        , -0.00997543,  1.04552192],
       [ 2.        ,  3.        ,  0.04555814,  0.86727825],
       [ 4.        ,  5.        ,  1.55400586, -0.58429776]])

In [25]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        , -0.00997543,  1.04552192],
       [ 2.        ,  3.        ,  0.04555814,  0.86727825],
       [ 4.        ,  5.        ,  1.55400586, -0.58429776]])

In [26]:
np.any([True, False])

True

In [27]:
arr = np.array([[7, 8, 9], [10, 11, 12]])


In [28]:
np.concatenate([np.zeros((1, 3)), arr], axis=0)

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [30]:
np.vstack([np.zeros((1, 3)), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [38]:
np.r_[np.zeros((1, 3)), arr]

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [34]:
np.random.uniform(2, 10, (2, 2))

array([[ 7.95370601,  5.47594583],
       [ 9.11238581,  4.24716633]])

In [36]:
arr.argmin(axis=1)

array([0, 0])

In [37]:
np.ceil(arr)

array([[  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [40]:
arr = np.random.randn(2, 2)

In [41]:
np.tile(arr, (3, 2))

array([[-0.25268891,  1.62453041, -0.25268891,  1.62453041],
       [ 0.40284071, -0.79241224,  0.40284071, -0.79241224],
       [-0.25268891,  1.62453041, -0.25268891,  1.62453041],
       [ 0.40284071, -0.79241224,  0.40284071, -0.79241224],
       [-0.25268891,  1.62453041, -0.25268891,  1.62453041],
       [ 0.40284071, -0.79241224,  0.40284071, -0.79241224]])

In [42]:
a = np.array([6, 0, 0, 4, 2, 5, 6])
b = [2, 3, 6]

In [43]:
np.union1d(a, b)

array([0, 2, 3, 4, 5, 6])

In [45]:
arr = np.random.randn(2, 2)
arr

array([[-2.25726262, -0.87961334],
       [-2.86624465, -1.18609546]])

In [49]:
arr.repeat(2, axis=1)

array([[-2.25726262, -2.25726262, -0.87961334, -0.87961334],
       [-2.86624465, -2.86624465, -1.18609546, -1.18609546]])

In [50]:
np.array([True, False], dtype=np.bool)

array([ True, False], dtype=bool)

In [51]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])


In [52]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [53]:
arr = np.random.randn(2, 2)


In [54]:
arr

array([[-0.61712933,  0.33765703],
       [ 0.47822833, -0.59237887]])

In [55]:
arr.repeat((2, 3), axis=0)

array([[-0.61712933,  0.33765703],
       [-0.61712933,  0.33765703],
       [ 0.47822833, -0.59237887],
       [ 0.47822833, -0.59237887],
       [ 0.47822833, -0.59237887]])

In [56]:
X = np.random.randn(5, 5)
X

array([[ 1.72681908, -0.48241628,  1.21287266,  0.81933297,  0.52428985],
       [-0.32142441,  0.38423321, -0.14798549, -0.80564347, -0.05555809],
       [ 1.91884007,  1.80518787, -0.7944511 ,  1.49757497,  0.18272966],
       [-1.78474531, -0.29297226, -1.53132389,  1.13961358,  0.42204671],
       [ 2.22373081, -1.39981774,  1.63131007, -1.23942919, -1.07951304]])

In [57]:
np.linalg.inv(X)

array([[ 0.47146855,  1.18218818,  0.31119329,  0.57061489,  0.44390055],
       [-0.45449759, -0.77457363,  0.06671141, -0.85754865, -0.50484807],
       [-0.37714291, -1.89495725, -0.39495435, -1.24447603, -0.63903709],
       [-0.4386305 , -1.92649444, -0.01832513, -0.47360537, -0.30214484],
       [ 1.4942361 ,  2.78794297, -0.0212633 ,  0.95059505,  0.02392756]])

In [58]:
np.linalg.pinv(X)

array([[ 0.47146855,  1.18218818,  0.31119329,  0.57061489,  0.44390055],
       [-0.45449759, -0.77457363,  0.06671141, -0.85754865, -0.50484807],
       [-0.37714291, -1.89495725, -0.39495435, -1.24447603, -0.63903709],
       [-0.4386305 , -1.92649444, -0.01832513, -0.47360537, -0.30214484],
       [ 1.4942361 ,  2.78794297, -0.0212633 ,  0.95059505,  0.02392756]])

In [59]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))

In [60]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        , -0.00997543,  1.04552192],
       [ 2.        ,  3.        ,  0.04555814,  0.86727825],
       [ 4.        ,  5.        ,  1.55400586, -0.58429776]])

In [61]:
np.concatenate([arr1, arr2], axis=1)

array([[ 0.        ,  1.        , -0.00997543,  1.04552192],
       [ 2.        ,  3.        ,  0.04555814,  0.86727825],
       [ 4.        ,  5.        ,  1.55400586, -0.58429776]])

In [62]:
np.hstack([arr1, arr2])

array([[ 0.        ,  1.        , -0.00997543,  1.04552192],
       [ 2.        ,  3.        ,  0.04555814,  0.86727825],
       [ 4.        ,  5.        ,  1.55400586, -0.58429776]])

In [63]:
np.concatenate([arr1, arr2], axis=0)

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.00997543,  1.04552192],
       [ 0.04555814,  0.86727825],
       [ 1.55400586, -0.58429776]])

In [64]:
np.vstack([arr1, arr2])

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.00997543,  1.04552192],
       [ 0.04555814,  0.86727825],
       [ 1.55400586, -0.58429776]])

In [65]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.00997543,  1.04552192],
       [ 0.04555814,  0.86727825],
       [ 1.55400586, -0.58429776]])

In [66]:
arr = np.array([[7, 8, 9], [10, 11, 12]])


In [67]:
np.concatenate([np.zeros((1, 3)), arr], axis=0)

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [68]:
np.vstack([np.zeros((1, 3)), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [69]:
np.r_[np.zeros((1, 3)), arr]

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [71]:
arr.argmin(axis=1)

array([0, 0])

In [72]:
arr = np.random.randn(2, 2)


In [73]:
arr.repeat(2, axis=0)

array([[-0.77991794, -0.38141269],
       [-0.77991794, -0.38141269],
       [ 0.22746615, -0.30715467],
       [ 0.22746615, -0.30715467]])

In [74]:
arr = np.arange(3)

In [75]:
arr.repeat((2, 3, 4))

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [76]:
arr = np.random.randn(4, 3)

In [77]:
arr

array([[-1.06291081,  1.4983358 ,  0.6149075 ],
       [ 0.36714461,  0.99491668,  0.38077784],
       [ 0.1261252 , -0.93195222, -0.0536848 ],
       [-0.27829397, -1.73089176, -0.45852303]])

In [85]:
arr.mean(axis=0)

array([-0.21198374, -0.04239788,  0.12086938])

In [84]:
arr - arr.mean(axis=0)

array([[-0.85092707,  1.54073367,  0.49403813],
       [ 0.57912835,  1.03731455,  0.25990846],
       [ 0.33810894, -0.88955434, -0.17455418],
       [-0.06631023, -1.68849389, -0.57939241]])

In [86]:
arr.max(axis=0)

array([ 0.36714461,  1.4983358 ,  0.6149075 ])

In [87]:
np.zeros((1, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [89]:
arr1 = np.array([True, False, True])
arr2 = np.array([False, False, True])

In [90]:
np.logical_not(arr1)

array([False,  True, False], dtype=bool)

In [93]:
arr.cumsum(axis=1)

array([[-1.06291081,  0.43542499,  1.05033249],
       [ 0.36714461,  1.36206129,  1.74283913],
       [ 0.1261252 , -0.80582702, -0.85951182],
       [-0.27829397, -2.00918574, -2.46770877]])

In [94]:
arr = np.random.randn(2, 2)


In [95]:
np.tile(arr, (1, 2))

array([[ 0.83646421,  0.09702583,  0.83646421,  0.09702583],
       [ 1.65884105, -0.16976787,  1.65884105, -0.16976787]])

In [96]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [97]:
arr2d[:2, 2]

array([3, 6])

In [98]:
arr2d[1, :2]

array([4, 5])

In [100]:
arr2d[0, 2]

3

In [101]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [102]:
np.greater
np.greater_equal
np.equal
np.less
np.less_equal

<ufunc 'less_equal'>

In [103]:
np.in1d([1, 2], [1, 2, 3])

array([ True,  True], dtype=bool)

In [104]:
arr = np.random.randn(4, 2)
arr

array([[-2.1253738 , -0.28024275],
       [-0.57778548, -0.85754321],
       [-1.0928604 ,  1.11048459],
       [-1.02433533, -0.0504057 ]])

In [108]:
np.split(arr, [2], axis=0)

[array([[-2.1253738 , -0.28024275],
        [-0.57778548, -0.85754321]]), array([[-1.0928604 ,  1.11048459],
        [-1.02433533, -0.0504057 ]])]

In [109]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [111]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [112]:
np.random.normal(1, 2, (2, 3))

array([[ 2.32152743,  2.51568925, -0.21858004],
       [ 1.63424709, -1.50314361, -1.29901438]])

In [113]:
arr = np.random.randn(4, 3)

In [114]:
arr.mean(axis=0)

array([-0.50940913, -0.56630429,  0.74023002])

In [116]:
(arr - arr.mean(axis=0)).mean()

-9.2518585385429707e-18

In [117]:
arr = np.random.randn(2, 2)


In [120]:
arr.repeat(2, axis=1)

array([[-1.11140651, -1.11140651,  0.24207357,  0.24207357],
       [ 1.55050908,  1.55050908, -1.11395607, -1.11395607]])

In [121]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [122]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
arr.cumprod(axis=1)

array([[-1.11140651, -0.26904214],
       [ 1.55050908, -1.727199  ]])

In [125]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [127]:
arr = np.arange(32).reshape((8, 4))
arr[[1, 5, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [ 8,  9, 10, 11]])

In [128]:
arr = np.random.randn(5, 3)
arr

array([[ -4.19583875e-01,   3.42627469e-01,   5.81124485e-01],
       [  1.92087137e-01,   2.00407052e+00,   6.75397741e-04],
       [ -2.69038727e+00,   9.85030498e-01,  -6.75953420e-01],
       [ -1.21591337e+00,   1.06822817e+00,  -9.52484549e-01],
       [  2.00085393e-01,  -1.89828850e-01,   1.17584288e+00]])

In [130]:
np.split(arr, [1, 2], axis=1)

[array([[-0.41958388],
        [ 0.19208714],
        [-2.69038727],
        [-1.21591337],
        [ 0.20008539]]), array([[ 0.34262747],
        [ 2.00407052],
        [ 0.9850305 ],
        [ 1.06822817],
        [-0.18982885]]), array([[  5.81124485e-01],
        [  6.75397741e-04],
        [ -6.75953420e-01],
        [ -9.52484549e-01],
        [  1.17584288e+00]])]

In [136]:
np.hsplit(arr, (1, 2))

[array([[-0.41958388],
        [ 0.19208714],
        [-2.69038727],
        [-1.21591337],
        [ 0.20008539]]), array([[ 0.34262747],
        [ 2.00407052],
        [ 0.9850305 ],
        [ 1.06822817],
        [-0.18982885]]), array([[  5.81124485e-01],
        [  6.75397741e-04],
        [ -6.75953420e-01],
        [ -9.52484549e-01],
        [  1.17584288e+00]])]

In [137]:
arr = np.random.randn(2, 2)


In [138]:
np.repeat(arr, (2, 3), axis=1)

array([[ 0.12666773,  0.12666773, -0.88394056, -0.88394056, -0.88394056],
       [ 0.60363728,  0.60363728, -0.96785577, -0.96785577, -0.96785577]])

In [139]:
arr.shape

(2, 2)

In [140]:
arr = np.arange(3)


In [141]:
np.repeat(arr, 2)

array([0, 0, 1, 1, 2, 2])

In [144]:
np.random.shuffle(arr)
arr

array([1, 2, 0])

In [146]:
np.random.shuffle(arr2d)
arr2d

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [149]:
arr2d.sort(axis=0)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [151]:
arr = np.random.randn(4, 2)
arr

array([[ 0.23232492,  0.88493469],
       [ 1.5893647 ,  0.04329975],
       [ 0.88043786, -1.54992624],
       [ 0.2217131 ,  0.82269625]])

In [152]:
np.split(arr, (2), axis=0)

[array([[ 0.23232492,  0.88493469],
        [ 1.5893647 ,  0.04329975]]), array([[ 0.88043786, -1.54992624],
        [ 0.2217131 ,  0.82269625]])]

In [153]:
np.vsplit(arr, 2)

[array([[ 0.23232492,  0.88493469],
        [ 1.5893647 ,  0.04329975]]), array([[ 0.88043786, -1.54992624],
        [ 0.2217131 ,  0.82269625]])]

In [154]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [155]:
arr = np.random.randn(5, 2)
arr

array([[ 0.12614513,  0.72891563],
       [ 0.29529613,  0.07686583],
       [ 1.26055517,  0.02204858],
       [-0.19068856, -0.5381824 ],
       [ 0.92503997,  0.40374647]])

In [156]:
np.split(arr, 2, axis=1)

[array([[ 0.12614513],
        [ 0.29529613],
        [ 1.26055517],
        [-0.19068856],
        [ 0.92503997]]), array([[ 0.72891563],
        [ 0.07686583],
        [ 0.02204858],
        [-0.5381824 ],
        [ 0.40374647]])]

In [158]:
np.array([1, 2, 3], dtype=np.int64)

array([1, 2, 3])

In [159]:
arr = np.random.randn(4, 2)
arr

array([[-0.40886643, -0.65239786],
       [-1.24807193, -0.15854336],
       [-1.18256081, -0.4648656 ],
       [-0.01651267, -1.81970868]])

In [162]:
np.split(arr, (2), axis=1)

[array([[-0.40886643],
        [-1.24807193],
        [-1.18256081],
        [-0.01651267]]), array([[-0.65239786],
        [-0.15854336],
        [-0.4648656 ],
        [-1.81970868]])]

In [163]:
np.hsplit(arr, 2)

[array([[-0.40886643],
        [-1.24807193],
        [-1.18256081],
        [-0.01651267]]), array([[-0.65239786],
        [-0.15854336],
        [-0.4648656 ],
        [-1.81970868]])]

In [165]:
arr = np.random.randn(2, 2)
np.repeat(arr, (2, 3), axis=1)

array([[-0.65523069, -0.65523069, -2.36364619, -2.36364619, -2.36364619],
       [ 1.11263576,  1.11263576,  0.4464006 ,  0.4464006 ,  0.4464006 ]])

In [166]:
arr = np.random.randn(5, 2)
arr

array([[ 0.15068188,  1.37945318],
       [ 0.40260416, -0.18633424],
       [-0.47645874, -0.66675562],
       [ 0.51518733, -0.87799506],
       [-1.09186938, -0.2990903 ]])

In [167]:
np.split(arr, (1, 3), axis=0)

[array([[ 0.15068188,  1.37945318]]), array([[ 0.40260416, -0.18633424],
        [-0.47645874, -0.66675562]]), array([[ 0.51518733, -0.87799506],
        [-1.09186938, -0.2990903 ]])]

In [168]:
arr2d[1, :2a = np.array([6, 0, 0, 4, 2, 5, 6])
b = [2, 3, 6]]

array([4, 5])

In [169]:
a = np.array([6, 0, 0, 4, 2, 5, 6])
b = [2, 3, 6]

In [170]:
np.intersect1d(a, b)

array([2, 6])

In [171]:
bools = np.array([False, False, True, False])

In [173]:
all(bools)

False

In [174]:
arr = np.random.randn(2, 2)


In [175]:
np.tile(arr, (2, 1))

array([[ 0.46694059, -2.22002021],
       [ 0.11554018,  0.82325161],
       [ 0.46694059, -2.22002021],
       [ 0.11554018,  0.82325161]])

In [1]:
import numpy as np

In [2]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])


In [3]:
arr.cumprod(axis=0)

array([[  0,   1,   2],
       [  0,   4,  10],
       [  0,  28,  80],
       [  0, 280, 880]])

In [4]:
arr = np.random.randn(7) * 5

In [5]:
np.sign(arr)

array([-1.,  1., -1.,  1.,  1.,  1.,  1.])

In [6]:
X = np.random.randn(5, 5)

In [7]:
np.diag(X)

array([ 0.59344247, -0.46376318,  0.13524113, -2.71936185,  0.82294115])

In [8]:
np.diag(np.arange(4))

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [9]:
arr = np.arange(15)
arr

other_arr = np.ones((3, 5))

In [10]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
np.random.randn(4, 4)

array([[-1.27103845,  0.76425009,  1.01748155, -1.94869074],
       [-0.06782894,  1.64278628,  1.03146948,  0.24231442],
       [-1.38184263, -0.57361188,  0.75833534,  0.40173115],
       [ 1.69204454, -0.79433883,  1.24396414, -0.61615581]])

In [13]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

In [14]:
arr.min(axis=1)

array([0, 3, 6, 9])

In [15]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]])

In [16]:
arr.argmax(axis=1)

array([2, 2, 2, 2])

In [17]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])


In [18]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [19]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [20]:
np.c_[arr1, arr2]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [22]:
np.where(cond, xarr, yarr)

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [23]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7, 4)


In [24]:
data[names == "Bob"]

array([[-1.08338415, -0.85654129, -0.22531492,  0.2094714 ],
       [-0.27874515, -1.12852631, -1.3781621 , -0.86990063]])

In [25]:
np.empty((1, 10))

array([[  1.72723371e-077,   2.32035393e+077,   2.47032823e-323,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          1.72723371e-077,   4.33529792e-311,   9.88131292e-324,
          7.55635054e-309]])

In [26]:
arr.sum(axis=0)

array([18, 22, 26])

In [27]:
np.arange(32).reshape((8, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [28]:
np.array([1, 2, 3], dtype=np.float64)

array([ 1.,  2.,  3.])

In [29]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

In [31]:
arr[[2, 3, 4]]

array([[ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.]])

In [32]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [33]:
numeric_strings.astype(np.float64)

array([  1.25,  -9.6 ,  42.  ])

In [34]:
X = np.random.randn(5, 5)
X

array([[ 0.40948767, -0.346868  , -0.48142549,  1.06634368, -0.27333008],
       [ 0.46198042,  1.74068889,  0.15896161, -0.46484376, -0.95290845],
       [ 0.14793735, -1.12179959,  0.63500727, -0.42673952,  0.93519694],
       [ 0.40308   ,  0.15281693, -0.65089023, -0.33253113,  1.13225529],
       [-0.16638626, -2.31198986, -1.62086486,  0.81611373,  1.06935253]])

In [35]:
np.dot(X, X)

array([[ 0.4115133 ,  0.58912721, -0.80902674,  0.22567639,  0.68346757],
       [ 0.98803747,  4.8235072 ,  2.00233343, -1.00746031, -3.18164674],
       [-0.69134372, -4.94374859, -1.08437692,  1.31336213,  2.13927058],
       [-0.18306463, -1.81221957, -2.20187254,  1.67117244, -0.03023506],
       [-1.22498005, -4.49607167, -3.58115241,  2.19030626,  2.80032909]])

In [36]:
X.dot(X)

array([[ 0.4115133 ,  0.58912721, -0.80902674,  0.22567639,  0.68346757],
       [ 0.98803747,  4.8235072 ,  2.00233343, -1.00746031, -3.18164674],
       [-0.69134372, -4.94374859, -1.08437692,  1.31336213,  2.13927058],
       [-0.18306463, -1.81221957, -2.20187254,  1.67117244, -0.03023506],
       [-1.22498005, -4.49607167, -3.58115241,  2.19030626,  2.80032909]])

In [37]:
X @ X

array([[ 0.4115133 ,  0.58912721, -0.80902674,  0.22567639,  0.68346757],
       [ 0.98803747,  4.8235072 ,  2.00233343, -1.00746031, -3.18164674],
       [-0.69134372, -4.94374859, -1.08437692,  1.31336213,  2.13927058],
       [-0.18306463, -1.81221957, -2.20187254,  1.67117244, -0.03023506],
       [-1.22498005, -4.49607167, -3.58115241,  2.19030626,  2.80032909]])

In [38]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])


In [39]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [40]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [41]:
np.c_[arr1, arr2]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [42]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
np.r_[arr1, arr2]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
data = np.random.randn(7, 4)


In [47]:
data[data > 0] = -1

In [48]:
data

array([[-1.        , -0.04000114, -1.        , -1.        ],
       [-1.        , -1.        , -0.43557054, -1.        ],
       [-0.40907585, -1.        , -1.51506028, -1.        ],
       [-1.        , -1.        , -1.        , -1.        ],
       [-1.        , -0.55252183, -1.        , -1.        ],
       [-1.        , -0.58338836, -1.        , -0.1769378 ],
       [-0.50079938, -1.        , -0.13286858, -0.90927074]])

In [50]:
np.random.randn(4, 4)

array([[-0.81902641, -1.26346352, -0.12218402,  0.98945277],
       [ 0.34004596,  1.17450092, -1.4579662 , -1.12344051],
       [-1.21079758,  0.32040318, -0.21564717,  1.40768997],
       [ 0.03555122,  0.90497969,  1.6753764 ,  0.77057996]])

In [51]:
np.random.uniform(0, 10, (2, 2))

array([[ 9.01855653,  7.83702652],
       [ 8.30200489,  4.09581374]])

In [52]:
arr = np.random.randn(5, 3)
arr

array([[ 2.07025675, -1.38282932, -0.43812323],
       [-0.04631189, -0.94587845,  0.19400007],
       [-0.53256197,  0.92815947, -0.57082712],
       [-0.91650512, -1.19238545,  0.42433382],
       [-1.22289873, -0.54090946,  3.21659251]])

In [55]:
arr.sort(axis=1)
arr

array([[-1.38282932, -0.91650512,  0.19400007],
       [-1.22289873, -0.54090946,  0.42433382],
       [-1.19238545, -0.53256197,  0.92815947],
       [-0.94587845, -0.43812323,  2.07025675],
       [-0.57082712, -0.04631189,  3.21659251]])

In [56]:
arr1 ** arr2

array([[         1,        256,      19683],
       [   1048576,   48828125, 2176782336]])

In [57]:
np.power(arr1, arr2)

array([[         1,        256,      19683],
       [   1048576,   48828125, 2176782336]])

In [58]:
arr.sum(axis=1)

array([-2.10533436, -1.33947436, -0.79678796,  0.68625507,  2.59945351])

In [59]:
X.T

array([[ 0.40948767,  0.46198042,  0.14793735,  0.40308   , -0.16638626],
       [-0.346868  ,  1.74068889, -1.12179959,  0.15281693, -2.31198986],
       [-0.48142549,  0.15896161,  0.63500727, -0.65089023, -1.62086486],
       [ 1.06634368, -0.46484376, -0.42673952, -0.33253113,  0.81611373],
       [-0.27333008, -0.95290845,  0.93519694,  1.13225529,  1.06935253]])

In [60]:
arr.sum(axis=0)

array([-5.31481906, -2.47441167,  6.83334263])

In [61]:
arr = np.arange(100)

In [62]:
np.random.shuffle(arr)

In [63]:
a = np.array([6, 0, 0, 4, 2, 5, 6])
b = [2, 3, 6]

In [65]:
np.setdiff1d(a, b)

array([0, 4, 5])

In [66]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])


In [67]:
np.c_[arr1, arr2]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [69]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])


In [70]:
arr.max(axis=1)

array([ 2,  5,  8, 11])

In [71]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
arr.reshape((3, 4arr = np.random.randn(5, 4)
arr))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
arr = np.random.randn(5, 4)
arr

array([[ 1.26673346, -0.66185312,  0.46474027, -1.04697996],
       [ 0.73498239, -0.66803219, -0.68837917, -0.8960283 ],
       [-0.14551333, -1.17895549,  0.83057579,  1.81255631],
       [ 0.63183575, -0.02046056, -1.30278331,  0.42655489],
       [ 2.26922705, -0.3665218 ,  0.09098541, -0.35655606]])

In [75]:
arr.sum(axis=1)

array([ 0.02264065, -1.51745727,  1.31866329, -0.26485323,  1.63713461])

In [76]:
np.sort(arr)

array([[-1.04697996, -0.66185312,  0.46474027,  1.26673346],
       [-0.8960283 , -0.68837917, -0.66803219,  0.73498239],
       [-1.17895549, -0.14551333,  0.83057579,  1.81255631],
       [-1.30278331, -0.02046056,  0.42655489,  0.63183575],
       [-0.3665218 , -0.35655606,  0.09098541,  2.26922705]])

In [77]:

ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
ints

array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [78]:
np.unique(ints)

array([1, 2, 3, 4])

In [79]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])


In [80]:
arr.argmin(axis=0)

array([0, 0, 0])

In [81]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [82]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [85]:
X = np.random.randn(5, 5)
X

array([[ 0.60233021,  1.88205511, -1.16136576, -1.05306463, -0.22869904],
       [ 0.56195481,  1.40188149, -1.56394513, -0.72486916, -0.60660851],
       [-0.70844182,  0.40162022,  0.79147315,  0.10225323,  0.07353188],
       [-0.80379143,  0.55314504,  0.52699804, -1.20062558,  0.09250382],
       [-0.732261  ,  0.61976962,  2.13602603,  0.09158377, -1.34115303]])

In [86]:
np.linalg.det(X)

2.777038043624759

In [87]:
arr = np.arange(10)


In [88]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr[2:5] = 10

In [90]:
arr

array([ 0,  1, 10, 10, 10,  5,  6,  7,  8,  9])

In [91]:
arr[4:10].copy()

array([10,  5,  6,  7,  8,  9])

In [92]:
arr = np.random.randn(6)

In [93]:
arr.sort(axis=0)

In [94]:
a = np.array([6, 0, 0, 4, 2, 5, 6])
b = [2, 3, 6]

In [95]:
np.setdiff1d(a, b)

array([0, 4, 5])

In [96]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])


In [97]:
arr.argmin(axis=1)

array([0, 0, 0, 0])

In [98]:
arr.argmin(axis=0)

array([0, 0, 0])

In [99]:
np.r_[arr1, arr2]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
a

array([6, 0, 0, 4, 2, 5, 6])

In [101]:
np.logical_and(arr1, arr2)

array([[ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [102]:
np.random.seed(222)

In [103]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [104]:
np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

In [105]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [106]:
x @ y

array([[  28.,   64.],
       [  67.,  181.]])