In [1]:
import numpy as nparr = np.arange(15)
arr


In [2]:
arr = np.arange(15)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
arr = np.arange(12)
arr.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
arr = np.arange(15)
arr

other_arr = np.ones((3, 5))

In [7]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [13]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [15]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [18]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [19]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [22]:
np.vstack([np.zeros(3), arr2])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [24]:
np.hstack([, arr2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [28]:
np.hstack([np.zeros((2, 1)), arr2])

array([[  0.,   7.,   8.,   9.],
       [  0.,  10.,  11.,  12.]])

In [40]:
arr = np.zeros((9, 9))
arr

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [47]:
np.split(arr, [3, 6])

[array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])]

In [48]:
arr

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [49]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.hstack([np.zeros((2, 1)), arr1])

array([[ 0.,  1.,  2.,  3.],
       [ 0.,  4.,  5.,  6.]])

In [53]:
arr = np.arange(14)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [54]:
arr.reshape((5, -1))

ValueError: total size of new array must be unchanged

In [55]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [57]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
arr = np.random.randn(5, 2)
arr

array([[-1.49974615,  0.11958545],
       [ 0.62916522, -0.85513115],
       [-0.30497835, -2.08570565],
       [ 0.96118413,  0.16519706],
       [ 0.49329683, -0.39081569]])

In [60]:
np.split(arr, [1, 3], axis=0)

[array([[-1.49974615,  0.11958545]]), array([[ 0.62916522, -0.85513115],
        [-0.30497835, -2.08570565]]), array([[ 0.96118413,  0.16519706],
        [ 0.49329683, -0.39081569]])]

In [61]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [64]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [66]:
np.vstack([np.zeros((1, 3)), arr1])

array([[ 0.,  0.,  0.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [67]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [70]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [71]:
arr = np.random.randn(5, 2)
arr

array([[ 1.2332415 , -0.2445266 ],
       [-1.06300004, -0.6623608 ],
       [ 0.04831362,  0.00611901],
       [-1.25567794,  0.9246389 ],
       [-0.56738958, -1.3307753 ]])

In [79]:
arr = np.random.randn(5, 2)
arr

array([[-1.30909914,  0.21290221],
       [-0.96549824,  0.58622281],
       [-1.80163289,  0.65000129],
       [ 0.06203538,  0.44355528],
       [-0.97412747, -0.2800208 ]])

In [84]:
np.hsplit(arr, 2)

[array([[-1.30909914],
        [-0.96549824],
        [-1.80163289],
        [ 0.06203538],
        [-0.97412747]]), array([[ 0.21290221],
        [ 0.58622281],
        [ 0.65000129],
        [ 0.44355528],
        [-0.2800208 ]])]

In [88]:
arr = np.array([[7, 8, 9], [10, 11, 12]])


In [90]:
np.vstack([np.zeros((1, 3)), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [93]:
np.hstack([np.zeros((2, 1)), arr])

array([[  0.,   7.,   8.,   9.],
       [  0.,  10.,  11.,  12.]])

In [94]:
arr = np.random.randn(5, 2)
arr

array([[ 1.75673476, -0.89272634],
       [ 0.58680633, -1.1067339 ],
       [ 0.34145327, -0.42500806],
       [-0.52271458,  1.48474646],
       [-1.55848716,  0.42314731]])

In [2]:
import numpy as np

In [3]:
arr = np.random.randn(5, 2)
arr


array([[ 0.32321501, -0.88586396],
       [ 2.54467649, -0.56897558],
       [ 0.00643053,  1.94591343],
       [-1.19185616, -1.04898502],
       [-0.86569321, -0.14659885]])

In [6]:
np.split(arr, [1], axis=1)

[array([[ 0.32321501],
        [ 2.54467649],
        [ 0.00643053],
        [-1.19185616],
        [-0.86569321]]), array([[-0.88586396],
        [-0.56897558],
        [ 1.94591343],
        [-1.04898502],
        [-0.14659885]])]

In [13]:

arr = np.array([[7, 8, 9], [10, 11, 12]])
arr

array([[ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.vstack([np.zeros(3), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [10]:
np.zeros((1, 3))

array([[ 0.,  0.,  0.]])

In [16]:
arr = np.random.randn(5, 2)
arr

array([[ 0.28201642, -0.16409466],
       [-0.6934574 , -0.5662858 ],
       [-2.08920205, -0.59654544],
       [-1.93527   ,  0.15938571],
       [-1.67707747, -0.26622623]])

In [17]:
arr

array([[ 0.28201642, -0.16409466],
       [-0.6934574 , -0.5662858 ],
       [-2.08920205, -0.59654544],
       [-1.93527   ,  0.15938571],
       [-1.67707747, -0.26622623]])

In [18]:
np.split(arr, [1, 3], axis=0)

[array([[ 0.28201642, -0.16409466]]), array([[-0.6934574 , -0.5662858 ],
        [-2.08920205, -0.59654544]]), array([[-1.93527   ,  0.15938571],
        [-1.67707747, -0.26622623]])]

In [22]:
np.split(arr, 2, axis=1)

[array([[ 0.28201642],
        [-0.6934574 ],
        [-2.08920205],
        [-1.93527   ],
        [-1.67707747]]), array([[-0.16409466],
        [-0.5662858 ],
        [-0.59654544],
        [ 0.15938571],
        [-0.26622623]])]

In [24]:
arr = np.array([[7, 8, 9], [10, 11, 12]])
arr

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.vstack([np.zeros((1, 3)), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [26]:
arr = np.random.randn(5, 2)
arr


array([[ 0.61220314,  0.49338483],
       [ 1.41605856, -0.03230607],
       [-2.36236102,  0.74844977],
       [-0.22661396, -0.56641722],
       [ 0.92661266, -1.2900691 ]])

In [30]:
np.vsplit(arr, [3])

[array([[ 0.61220314,  0.49338483],
        [ 1.41605856, -0.03230607],
        [-2.36236102,  0.74844977]]), array([[-0.22661396, -0.56641722],
        [ 0.92661266, -1.2900691 ]])]

In [31]:
np.hsplit(arr, 2)

[array([[ 0.61220314],
        [ 1.41605856],
        [-2.36236102],
        [-0.22661396],
        [ 0.92661266]]), array([[ 0.49338483],
        [-0.03230607],
        [ 0.74844977],
        [-0.56641722],
        [-1.2900691 ]])]

In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [35]:
data[names =arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
= "Bob"]

array([[-0.81720561,  0.09449279, -0.49838219, -0.83042186],
       [-0.85431558, -0.95369348,  0.61670636,  1.00781776]])

In [36]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i


In [38]:
arr[[1, 3, 2]]

array([[ 1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.],
       [ 2.,  2.,  2.,  2.]])

In [39]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [40]:
np.round(arr)

array([  4.,  -1.,  -3.,   0.,  13.,  10.])

In [42]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [44]:
np.split(arr, (1, 2), axis=0)

[array([[ 0.70867955,  1.00511062]]),
 array([[ 0.37102022, -0.08774434]]),
 array([[ 0.41741244,  0.40032181],
        [ 0.55841025, -0.33390613],
        [-0.4910635 ,  0.80792952]])]

In [43]:
arr = np.random.randn(5, 2)
arr

array([[ 0.70867955,  1.00511062],
       [ 0.37102022, -0.08774434],
       [ 0.41741244,  0.40032181],
       [ 0.55841025, -0.33390613],
       [-0.4910635 ,  0.80792952]])

In [45]:
arr = np.array([[7, 8, 9], [10, 11, 12]])


In [48]:
np.vstack([np.zeros((1, 3)), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [54]:

arr = np.random.randn(5, 2)

In [64]:
np.vsplit(arr, 2)

ValueError: array split does not result in an equal division

In [65]:
arr

array([[ 0.9090176 ,  0.38876863],
       [ 0.15299854,  0.6795883 ],
       [-1.64397739, -1.15456343],
       [ 1.00514066,  0.4829136 ],
       [-0.48850266, -0.38681791]])

In [73]:
np.array_split(arr, 2, axis=1)

[array([[ 0.9090176 ],
        [ 0.15299854],
        [-1.64397739],
        [ 1.00514066],
        [-0.48850266]]), array([[ 0.38876863],
        [ 0.6795883 ],
        [-1.15456343],
        [ 0.4829136 ],
        [-0.38681791]])]

In [76]:
arr = np.random.randn(5, 3)
arr

array([[-2.6883198 , -0.44183496, -0.83032391],
       [-0.1402041 ,  0.81076596,  2.6195273 ],
       [-0.90814479,  0.80623877,  0.17068696],
       [ 0.2150241 ,  1.17498436,  0.60602313],
       [-0.01737514,  0.70729107, -0.37802615]])

In [83]:
np.hsplit(arr, (3))

[array([[-2.6883198 ],
        [-0.1402041 ],
        [-0.90814479],
        [ 0.2150241 ],
        [-0.01737514]]), array([[-0.44183496],
        [ 0.81076596],
        [ 0.80623877],
        [ 1.17498436],
        [ 0.70729107]]), array([[-0.83032391],
        [ 2.6195273 ],
        [ 0.17068696],
        [ 0.60602313],
        [-0.37802615]])]

In [84]:
arr = np.random.randn(4, 2)
arr

array([[ 0.58828651, -1.50500931],
       [ 0.85465522, -0.82676771],
       [ 0.41340477, -0.58396373],
       [-0.97425651, -2.69793707]])

In [89]:
arr = np.random.randn(4, 2)
arr

array([[-0.18437633,  0.11493545],
       [ 0.60163649,  2.20108592],
       [-0.42982118, -0.74837095],
       [ 1.22023166,  0.50169519]])

In [90]:
np.hsplit(arr, 2)

[array([[-0.18437633],
        [ 0.60163649],
        [-0.42982118],
        [ 1.22023166]]), array([[ 0.11493545],
        [ 2.20108592],
        [-0.74837095],
        [ 0.50169519]])]

In [91]:
np.hsplit(arr, 2)

[array([[-0.18437633],
        [ 0.60163649],
        [-0.42982118],
        [ 1.22023166]]), array([[ 0.11493545],
        [ 2.20108592],
        [-0.74837095],
        [ 0.50169519]])]

In [92]:
arr = np.array([[7, 8, 9], [10, 11, 12]])


In [93]:
np.vstack([np.zeros((1, 3)), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [94]:
arr = np.arange(32).reshape((8, 4))

In [95]:
arr[[1, 2, 3]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
arr = np.random.randn(4, 2)
arr

array([[ 1.91059653, -0.67984243],
       [-0.83466772, -1.41817465],
       [ 0.55871331, -0.2930296 ],
       [-1.03495109, -1.09615138]])

In [97]:
np.split(arr, (2), axis=0)

[array([[ 1.91059653, -0.67984243],
        [-0.83466772, -1.41817465]]), array([[ 0.55871331, -0.2930296 ],
        [-1.03495109, -1.09615138]])]

In [98]:
np.vsplit(arr, 2)

[array([[ 1.91059653, -0.67984243],
        [-0.83466772, -1.41817465]]), array([[ 0.55871331, -0.2930296 ],
        [-1.03495109, -1.09615138]])]

In [99]:
np.split(arr, (2), axis=1)

[array([[ 1.91059653],
        [-0.83466772],
        [ 0.55871331],
        [-1.03495109]]), array([[-0.67984243],
        [-1.41817465],
        [-0.2930296 ],
        [-1.09615138]])]

In [100]:
np.hsplit(arr, 2)

[array([[ 1.91059653],
        [-0.83466772],
        [ 0.55871331],
        [-1.03495109]]), array([[-0.67984243],
        [-1.41817465],
        [-0.2930296 ],
        [-1.09615138]])]

In [101]:
arr = np.array([[7, 8, 9], [10, 11, 12]])

In [102]:
np.vstack([np.zeros((1, 3)), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [103]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [104]:
numeric_strings.astype(np.float64)

array([  1.25,  -9.6 ,  42.  ])

In [106]:
np.array([1, 2, 3], dtype=np.string_)

array([b'1', b'2', b'3'], 
      dtype='|S1')

In [107]:
data = np.zeros((3, 6))

In [108]:
np.ones_like(data)

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [109]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


data = np.random.randn(7, 4)

In [110]:
data[names == "Bob"]

array([[ 1.02740156,  0.27183277, -1.49227701,  0.56078517],
       [ 1.5074157 , -0.10469428,  0.88431749,  0.68304079]])

In [111]:
np.zeros_like(data)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [112]:
np.arange(32).reshape((8, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [113]:
arr.sum()

57

In [114]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [115]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
arr.sum(axis=0)

array([ 9, 12, 15])

In [117]:
names = np.array(["Bob", "Joe", "Will", "Joe", "Joe"])

In [118]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

In [119]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])


In [120]:
arr.min(axis=1)

array([0, 3, 6, 9])

In [121]:
data.dtype

dtype('float64')

In [122]:
arr.min(axis=0)

array([0, 1, 2])

In [123]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336],
       [  9,  90, 990]])

In [124]:
arr.argmax(axis=0)

array([3, 3, 3])

In [125]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]])

In [126]:
arr / 3

array([[ 0.        ,  0.33333333,  0.66666667],
       [ 1.        ,  1.33333333,  1.66666667],
       [ 2.        ,  2.33333333,  2.66666667],
       [ 3.        ,  3.33333333,  3.66666667]])

In [127]:
arr.sort(axis=0)

In [128]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [134]:
np.random.shuffle(arr)
arr

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 6,  7,  8],
       [ 3,  4,  5]])

In [135]:
arr.sort(axis=0)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [136]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [137]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [138]:
arr = np.random.randn(4, 4)

In [139]:
np.where(arr > 0, 2, -2)

array([[-2, -2,  2,  2],
       [ 2,  2, -2, -2],
       [-2,  2, -2, -2],
       [ 2, -2,  2, -2]])

In [140]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [141]:
np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

In [142]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [143]:
x @ y

array([[  28.,   64.],
       [  67.,  181.]])

In [144]:
arr = np.random.randn(4, 2)
arr

array([[-0.98136098,  2.26815969],
       [-1.90904792, -1.34001553],
       [-1.28195635,  0.47478236],
       [ 0.45864564,  0.5877916 ]])

In [145]:
np.hsplit(arr, 2)

[array([[-0.98136098],
        [-1.90904792],
        [-1.28195635],
        [ 0.45864564]]), array([[ 2.26815969],
        [-1.34001553],
        [ 0.47478236],
        [ 0.5877916 ]])]

In [146]:
np.vsplit(arr, 2)

[array([[-0.98136098,  2.26815969],
        [-1.90904792, -1.34001553]]), array([[-1.28195635,  0.47478236],
        [ 0.45864564,  0.5877916 ]])]

In [147]:
np.split(arr, 2, axis=0)

[array([[-0.98136098,  2.26815969],
        [-1.90904792, -1.34001553]]), array([[-1.28195635,  0.47478236],
        [ 0.45864564,  0.5877916 ]])]

In [148]:
arr = np.array([[7, 8, 9], [10, 11, 12]])


In [149]:
np.vstack([np.zeros((1, 3)), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [150]:
np.random.normal(0, 1, (2, 3))

array([[-0.14947967,  1.28607722, -0.01725232],
       [ 0.54895839, -0.72526565,  0.30033145]])

In [151]:
np.random.randn(2, 3)

array([[-1.05644118,  2.1519719 , -0.06818367],
       [ 2.39940511, -1.61768746,  1.12815328]])

In [154]:
a = np.array([6, 0, 0, 4, 2, 5, 6])
b = [2, 3, 6]

In [156]:
np.union1d(a, b)

array([0, 2, 3, 4, 5, 6])

In [158]:
np.linalg.pinv(arr2d)

array([[ -6.38888889e-01,  -1.66666667e-01,   3.05555556e-01],
       [ -5.55555556e-02,   1.38777878e-16,   5.55555556e-02],
       [  5.27777778e-01,   1.66666667e-01,  -1.94444444e-01]])

In [159]:
np.diag(arr2d)

array([1, 5, 9])

In [160]:
np.zeros((4, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [161]:
np.linalg.inv(arr2d)

array([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
       [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
       [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

In [162]:
np.setdiff1d(a, b)

array([0, 4, 5])

In [163]:
arr2d[:, 0:1]

array([[1],
       [4],
       [7]])

In [164]:
np.linalg.eig(arr2d)

(array([  1.61168440e+01,  -1.11684397e+00,  -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [165]:
arr2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [167]:
np.random.shuffle(arr2d)

In [170]:
arr2d.sort(axis=1)

In [171]:
arr2d

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [172]:
np.linalg.inv(arr2d)

array([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
       [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
       [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

In [173]:
arr.sort(axis=1)

In [174]:
arr = np.random.randn(5, 3)
arr


array([[-1.18523013,  0.62905752, -0.31283576],
       [ 0.36039196, -1.11417512,  0.28012971],
       [-0.03527401,  0.33615235,  0.14613935],
       [ 0.73139917,  0.24992342,  0.28330778],
       [-0.36147327, -0.29833058, -0.99019537]])

In [175]:
arr.sort(axis=0)
arr

array([[-1.18523013, -1.11417512, -0.99019537],
       [-0.36147327, -0.29833058, -0.31283576],
       [-0.03527401,  0.24992342,  0.14613935],
       [ 0.36039196,  0.33615235,  0.28012971],
       [ 0.73139917,  0.62905752,  0.28330778]])

In [176]:
np.linalg.svd(arr2d)

(array([[-0.82633754,  0.38794278,  0.40824829],
        [-0.52058739, -0.24964395, -0.81649658],
        [-0.21483724, -0.88723069,  0.40824829]]),
 array([  1.68481034e+01,   1.06836951e+00,   6.44647231e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [ 0.77669099,  0.07568647, -0.62531805],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [179]:
np.logical_and(arr1, arr2)

array([False, False,  True], dtype=bool)

In [178]:
arr1 = np.array([True, False, True])
arr2 = np.array([False, False, True])

In [180]:
arr = np.random.randn(7) * 5

In [181]:
arr

array([ 0.68494402, -3.81024338,  2.1336363 , -9.4173658 ,  0.96714589,
       -2.95969982, -2.73971802])

In [182]:
np.sign(arr)

array([ 1., -1.,  1., -1.,  1., -1., -1.])

In [186]:
np.union1d(a, b)

array([0, 2, 3, 4, 5, 6])

In [184]:
a = np.array([6, 0, 0, 4, 2, 5, 6])
b = [2, 3, 6]

In [187]:
X = np.random.randn(5, 5)
X

array([[ 1.65650074,  0.01924987,  0.42227955,  2.11718796, -2.37304708],
       [ 0.85663971,  0.4030104 ,  0.01201764,  0.38534601,  1.71119218],
       [-0.17140416, -0.10893006, -1.61486686,  0.1002139 ,  0.39915833],
       [-0.57244543, -0.76880275,  0.70263911, -1.48785218, -0.41626145],
       [ 0.41122421,  0.23395016, -0.43718566,  0.61513613, -1.22146917]])

In [188]:
np.linalg.pinv(X)

array([[ 0.10219413,  1.06982482,  0.12711128,  0.86405108,  1.0472886 ],
       [-0.88676709,  0.287577  , -0.95271077, -0.43950156,  1.96411398],
       [ 0.09063985, -0.14162376, -0.5268124 , -0.14829748, -0.49611497],
       [ 0.44584706, -0.66390651,  0.15857517, -0.80653188, -1.46959334],
       [ 0.05664948,  0.13159525,  0.12873394, -0.14637791, -0.65243596]])

In [189]:
arr = np.random.randn(5, 3)
arr

array([[-1.73642171, -1.15389859, -0.86159876],
       [-0.02644156,  0.50672471,  0.82338481],
       [ 0.95915403,  0.66163988,  0.41032652],
       [-0.0302968 , -0.96226678,  1.27441379],
       [-2.24933538,  1.65819906, -0.33670571]])

In [190]:
arr = np.random.randn(5, 3)
arr

array([[-2.3057259 , -0.19981338,  0.5761746 ],
       [ 1.00752515,  0.31598141, -0.58832858],
       [-0.44781738,  0.40421747, -2.55512639],
       [-2.18269286, -0.94305986, -1.1505041 ],
       [ 0.82336223,  0.67025715,  0.08562095]])

In [191]:
arr.sort(axis=1)

In [192]:
arr

array([[-2.3057259 , -0.19981338,  0.5761746 ],
       [-0.58832858,  0.31598141,  1.00752515],
       [-2.55512639, -0.44781738,  0.40421747],
       [-2.18269286, -1.1505041 , -0.94305986],
       [ 0.08562095,  0.67025715,  0.82336223]])

In [193]:
arr.sort(axis=0)
arr

array([[-2.55512639, -1.1505041 , -0.94305986],
       [-2.3057259 , -0.44781738,  0.40421747],
       [-2.18269286, -0.19981338,  0.5761746 ],
       [-0.58832858,  0.31598141,  0.82336223],
       [ 0.08562095,  0.67025715,  1.00752515]])

In [194]:
np.random.seed(222)

In [195]:
np.isnan(X)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [196]:
X.trace()

-2.2646770644888736

In [197]:
arr = np.arange(12)
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
X.ndim

2

In [203]:
np.random.uniform(2, 20, (20, 2))

array([[ 14.33570933,  17.04213539],
       [ 13.76777467,   2.66639519],
       [  5.24280194,  15.69024954],
       [  6.03748311,  15.23243131],
       [  7.17482831,  15.19004009],
       [  3.93765463,   3.68933891],
       [ 16.09740332,  11.35275311],
       [ 18.29174298,   9.15929073],
       [  6.52913528,  18.8215006 ],
       [  3.484654  ,   9.6590473 ],
       [ 15.477069  ,   6.50745281],
       [ 10.38651007,   5.56081647],
       [  6.44372399,   8.36210917],
       [ 16.58629525,  16.57939352],
       [ 17.08513647,  18.57795985],
       [ 11.40710161,  14.24342882],
       [  4.85015683,   8.86769233],
       [ 16.02447648,  15.04129345],
       [ 18.85471122,   7.16111496],
       [  6.6368179 ,   7.4693648 ]])

In [206]:
np.empty((3, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [207]:
arr = np.arange(12)
arr.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [209]:
np.logical_or(arr1, arr2)


array([ True, False,  True], dtype=bool)

In [208]:
arr1 = np.array([True, False, True])
arr2 = np.array([False, False, True])

In [210]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])


In [212]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [215]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [216]:
arr = np.arange(15)
arr

other_arr = np.ones((3, 5))

In [217]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [218]:
arr = np.arange(100)

In [219]:
np.random.permutation(arr)

array([73,  1, 68, 74,  3, 65,  0, 13, 84, 70, 18, 85, 19, 50,  2, 78, 63,
        4, 41, 69, 80, 44, 87, 71, 42, 31, 24, 76, 56, 27, 98, 82, 11, 39,
       35, 49, 22, 99, 43, 32, 36, 30, 16, 75, 48, 28, 25, 58, 29, 95, 59,
       12, 10, 91, 33, 17,  5, 89, 81,  8, 90, 61, 45, 66, 20, 53, 93, 62,
       47, 97, 79, 26, 23,  9, 37, 40, 57, 83, 72, 54, 86, 77, 88,  6, 67,
       46, 14, 64, 15, 94,  7, 96, 60, 38, 51, 52, 55, 21, 92, 34])

In [220]:
arr = np.arange(15)
arr.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [221]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [223]:
t = arr.ravel()

In [224]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [225]:
t[0] = 100

In [226]:
t

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [227]:
arr

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14]])

In [228]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
ints

array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [229]:
np.unique(ints)

array([1, 2, 3, 4])

In [230]:
np.array([1, 2, 3], dtype=np.float64)

array([ 1.,  2.,  3.])

In [231]:
np.empty((1, 10))

array([[  2.96439388e-323,   0.00000000e+000,   0.00000000e+000,
          1.97626258e-323,   9.88131292e-324,   2.47032823e-323,
          2.96439388e-323,   9.88131292e-324,   1.48219694e-323,
          2.96439388e-323]])

In [232]:
np.random.normal(0, 1, (10, 2))

array([[-1.15950646, -1.67696918],
       [ 0.56943931,  2.04412812],
       [-1.04366702, -0.53404604],
       [-1.1065749 , -1.02611626],
       [-1.0886425 , -1.32940546],
       [ 0.01724515,  1.31447992],
       [-1.61993455,  0.04966855],
       [-0.44796211, -0.20002862],
       [ 1.42152408, -0.024052  ],
       [ 0.51299696, -0.41053983]])

In [233]:
arr = np.array([[7, 8, 9], [10, 11, 12]])

In [236]:
np.hstack([np.zeros((2, 1)), arr])

array([[  0.,   7.,   8.,   9.],
       [  0.,  10.,  11.,  12.]])

In [237]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [238]:
arr = np.arange(15).reshape((5, 3))
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [239]:
arr = np.array([1, 2, 3, 4, 5])


In [240]:
arr.astype(np.float64)

array([ 1.,  2.,  3.,  4.,  5.])

In [241]:
arr1.mean()

3.5

In [242]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
arr.sum(axis=0)

array([18, 22, 26])

In [243]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [245]:
arr2d[1, :2]

array([4, 5])

In [246]:
np.random.shuffle(arr2d)

In [247]:
np.in1d([1, 2], [1, 2, 3])

array([ True,  True], dtype=bool)

In [248]:
np.sort(arr2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [250]:
arr.mean(axis=1)

array([  1.,   4.,   7.,  10.])

In [251]:
a = np.array([6, 0, 0, 4, 2, 5, 6])
b = [2, 3, 6]

In [252]:
np.intersect1d(a, b)

array([2, 6])

In [253]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [254]:
arr2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [255]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [257]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [258]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [259]:
np.linalg.det(X)

-3.4058481600861112

In [260]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [261]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [262]:
np.random.normal(1, 3, 10)

array([ 2.12916005, -4.90929588,  5.84031961,  0.48884507,  0.28165584,
        1.6864555 , -2.57000066,  5.28690935, -1.01579846,  1.13154434])

In [263]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [264]:
np.random.normal(0, 1, (4, 4))

array([[-0.48856684,  0.73758096,  0.31054159, -1.27241956],
       [ 1.03138761, -0.67491774,  0.7490601 ,  0.09431015],
       [ 0.46051907, -1.71883478,  0.54151431, -0.13410804],
       [ 1.23925042,  1.45644096, -0.34643589, -0.47807437]])

In [265]:
np.random.randn(4, 4)

array([[-0.22253091, -0.23331628, -0.79758764, -0.71985172],
       [-0.9181421 , -0.25052995, -0.01664997,  0.15088129],
       [ 0.77389192,  1.5145908 , -1.82409105, -1.02974305],
       [-0.1456548 , -0.71792505,  1.39958112, -1.64564754]])

In [266]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i


In [267]:
arr[[1, 2]]

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.]])

In [268]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [270]:
np.random.uniform(19, 22, (3, 3))

array([[ 19.84405886,  21.77686818,  20.18824789],
       [ 19.76305247,  20.58545573,  20.60706167],
       [ 20.77909068,  21.04980089,  20.98800334]])

In [271]:
arr = np.array([[7, 8, 9], [10, 11, 12]])

In [272]:
np.hstack([np.zeros((2, 1)), arr])

array([[  0.,   7.,   8.,   9.],
       [  0.,  10.,  11.,  12.]])

In [273]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [274]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [275]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [276]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [278]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [279]:
arr2d[1, :2]

array([4, 5])

In [280]:
np.in1d([1, 2, 3], [1, 2])

array([ True,  True, False], dtype=bool)

In [281]:
np.intersect1d(a, b)

array([2, 6])

In [282]:
np.random.normal(0, 1, 100)

array([ 0.59578191,  0.11724486,  2.49814107,  0.24466136,  1.00254294,
       -0.87052253,  1.36080986, -0.60877137,  0.09304242,  1.97542299,
       -1.33860434,  0.86772472, -0.21192798,  0.13179591, -0.43861345,
        0.10643116, -0.40078566, -0.07109107, -0.38003948, -2.22098199,
       -0.3709966 , -0.70542212, -1.46546142, -0.60480863, -0.22092572,
       -0.05992337, -1.57079678,  0.76822835, -2.8894582 , -1.08479662,
        0.74402932, -2.37713905,  0.99924562,  0.62742955, -0.07730333,
       -0.82595021,  0.51500876, -1.24266641, -0.70845586,  0.08484725,
       -0.49422203, -0.56261808,  0.96236663, -0.7903481 ,  1.61844548,
        0.31772048,  2.5070994 ,  1.78610556,  0.0538938 ,  0.41328334,
       -0.92276385,  0.01046829, -2.30288526,  1.32080781, -1.33954708,
        0.65611674, -1.67279437,  0.88968697, -1.20321898,  0.56200333,
        0.19925379,  1.40436941, -0.70337038,  0.10351441,  0.15764649,
       -0.8637719 ,  0.35129898, -0.85527434, -1.37785552, -0.13

In [283]:
np.random.uniform(0, 20, 10)

array([  7.11779772,   9.00072537,   9.33672805,  15.89634469,
        12.701274  ,  15.81181962,  14.12526503,   3.46898808,
         2.86332029,   3.52907511])

In [284]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))

arr2 = np.random.randn(3, 2)

In [285]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.16732504, -0.97735205],
       [-0.61758318,  1.42093849],
       [ 0.11966868,  0.01388803]])

In [286]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        ,  0.16732504, -0.97735205],
       [ 2.        ,  3.        , -0.61758318,  1.42093849],
       [ 4.        ,  5.        ,  0.11966868,  0.01388803]])

In [287]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [288]:
np.tile(arr, (2, 3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [293]:
np.repeat(arr, (2, 3, 4))

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [295]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.16732504, -0.97735205],
       [-0.61758318,  1.42093849],
       [ 0.11966868,  0.01388803]])

In [296]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        ,  0.16732504, -0.97735205],
       [ 2.        ,  3.        , -0.61758318,  1.42093849],
       [ 4.        ,  5.        ,  0.11966868,  0.01388803]])

In [298]:
np.repeat(arr, (2, 3, 4))

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [301]:
arr = np.random.randn(2, 2)

In [303]:
np.repeat(arr, 2, axis=0)

array([[ 0.10587604,  0.68915235],
       [ 0.10587604,  0.68915235],
       [ 0.4786794 ,  0.87521301],
       [ 0.4786794 ,  0.87521301]])

In [304]:
arr = np.random.randn(2, 2)

In [307]:
np.repeat(arr, (2, 3), axis=1 )

array([[ 0.80578902,  0.80578902,  0.06865106,  0.06865106,  0.06865106],
       [ 0.84124228,  0.84124228,  1.80837862,  1.80837862,  1.80837862]])

In [308]:
arr = np.random.randn(2, 2)

In [314]:
np.tile(arr, (3, 2))

array([[-0.72197556, -0.57526037, -0.72197556, -0.57526037],
       [ 0.75052063, -0.26550467,  0.75052063, -0.26550467],
       [-0.72197556, -0.57526037, -0.72197556, -0.57526037],
       [ 0.75052063, -0.26550467,  0.75052063, -0.26550467],
       [-0.72197556, -0.57526037, -0.72197556, -0.57526037],
       [ 0.75052063, -0.26550467,  0.75052063, -0.26550467]])

In [317]:
arr = np.random.randn(4, 3)
arr

array([[-0.13676206,  0.60308548,  1.85843286],
       [ 0.77420344, -1.74715595,  0.79477859],
       [-1.10311092, -0.51316723,  0.76398052],
       [ 1.1298649 , -0.00540933,  0.10821663]])

In [316]:
arr.mean(axis=0)

array([ 0.23227432, -0.26296782,  0.11283026])

In [320]:
ar2r - arr.mean(axis=0)

array([[-0.3028109 ,  1.01874723,  0.97708071],
       [ 0.6081546 , -1.33149419, -0.08657356],
       [-1.26915976, -0.09750547, -0.11737163],
       [ 0.96381606,  0.41025243, -0.77313552]])

In [321]:
arr.mean(axis=1)

array([ 0.77491876, -0.05939131, -0.28409921,  0.41089074])

In [323]:
arr.T - arr.mean(axis=1)

array([[-0.91168082,  0.83359475, -0.81901171,  0.71897417],
       [-0.17183328, -1.68776464, -0.22906802, -0.41630006],
       [ 1.0835141 ,  0.8541699 ,  1.04807973, -0.3026741 ]])

In [324]:
arr = np.zeros((4, 3))
arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [326]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [327]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [328]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [329]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [330]:
arr = np.random.randn(5, 2)
arr

array([[-0.36198454, -0.27153001],
       [-0.81888588, -2.13041618],
       [-0.55254749,  1.41922339],
       [-1.50376005,  1.21649557],
       [ 0.44938416, -0.53930412]])

In [335]:
np.split(arr, [1], axis=1)

[array([[-0.36198454],
        [-0.81888588],
        [-0.55254749],
        [-1.50376005],
        [ 0.44938416]]), array([[-0.27153001],
        [-2.13041618],
        [ 1.41922339],
        [ 1.21649557],
        [-0.53930412]])]

In [339]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        , -2.13708591,  0.56708963],
       [ 2.        ,  3.        , -0.27683844, -0.27083117],
       [ 4.        ,  5.        ,  1.05856771, -0.46734674]])

In [337]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))

arr2 = np.random.randn(3, 2)


In [341]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-2.13708591,  0.56708963],
       [-0.27683844, -0.27083117],
       [ 1.05856771, -0.46734674]])

In [3]:
import numpy as np
arr1 = np.random.randn(7) * 5
arr2 = np.random.randn(7)


In [4]:
arr1 / arr2

array([ -1.98078382,   1.31448832,  -5.56438384, -36.36932254,
        26.3694821 ,   5.41339481,  -1.4178112 ])

In [5]:
np.divide(arr1, arr2)

array([ -1.98078382,   1.31448832,  -5.56438384, -36.36932254,
        26.3694821 ,   5.41339481,  -1.4178112 ])

In [7]:
np.maximum(arr1, arr2)

array([ 1.46127921,  2.392187  ,  5.38020247,  0.22437668,  2.59609982,
        3.3684875 ,  1.45522842])

In [8]:

arr = np.arange(15).reshape((3, 5))
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [10]:
arr[:] = 100

In [11]:
arr

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])